[package]
name = "sd-images"
version = "0.0.0"
authors = [
	"Jake Robinson <jake@spacedrive.com>",
	"Vítor Vasconcellos <vitor@spacedrive.com>",
]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
heif = ["dep:libheif-rs", "dep:libheif-sys"]
webp = ["dep:webp"]
rspc = ["dep:rspc"]                          # error conversion

[dependencies]
libheif-rs = { version = "0.19.2", optional = true }
libheif-sys = { version = "=1.14.2", optional = true }
image = "0.24.7"
webp = { version = "0.2.5", optional = true }
thiserror = "1.0.48"
resvg = "0.35.0"
rspc = { workspace = true, optional = true }
